version: "2"

services:
  backend:
    restart: always
    build: ./backend
    environment:
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - /usr/src/app/backend/project/static
      - ./backend:/home/flask/app/web/
    networks:
      - backend
    command: /usr/local/bin/gunicorn --enable-stdio-inheritance -w 4 -b :5000 project:app

  gui:
    restart: always
    build: ./frontend
    networks:
      - frontend
    command: pm2-runtime start yarn --name "QrespFrontend" --interpreter sh -- start

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
      - gui
    networks:
      - backend
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
